In [47]:
#Creating an array of numbers

import numpy as np

a = np.array([2,4,6,8,10])

print(a)

[ 2  4  6  8 10]


In [6]:
#Creating an array using the arrange(Start,Stop,Step) syntax

import numpy as np

a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
#Creating various arrays using NumPy functions

import numpy as np

#Creates an array of all zeroes:
p = np.zeros((3,3))
print(p)


#Creates an array of all ones:
q = np.ones((2,2))
print(q)

#Creates a constant array:
r = np.full((2,2), 4)
print(r)

#Creates a 2x2 identity matrix:
s = np.eye(4)
print(s)

#Creates an array filled with random values:
t = np.random.random((3,3))
print(t)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[4 4]
 [4 4]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.18638927 0.95120326 0.7625892 ]
 [0.18252865 0.23435815 0.30352685]
 [0.79255715 0.78597562 0.95130515]]


In [14]:
#Checking the data type

import numpy as np

a = np.arange(1,11)

print(type(a))
print(a.dtype)

#Shows the shape of the array in the form of a tuple of dimensions (x,y). A one dimensional array is a vector.
print(a.shape)

<class 'numpy.ndarray'>
int32
(10,)


In [22]:
#Selecting array elements

import numpy as np

#Creates a 2x2 array using the array() function
a = np.array([[5,6],[7,8]])
print(a)

#Selecting an element of choice = a[m,n], where:
#a is the variable representing the array, m is the row/record index, and n is the columnm/field index
#NOTE: index values start at 0
print(a[0,0])
print(a[1,0])
print(a[0,1])
print(a[1,1])

[[5 6]
 [7 8]]
5
7
6
8


In [32]:
#Manipulating Array Shapes

import numpy as np

arr = np.arange(12)
print(arr)

#reshapes the array into a specified dimension, in this case a 4x3 array:
reshaped_arr = arr.reshape(4,3)
print(reshaped_arr)

#to bring an n-dimensional array into a single dimension, the flatten() function can be used:
flattened_arr = reshaped_arr.flatten()
print(flattened_arr)

#ravel works in the same way as flatten(), but is faster because it returns the reference of the original array.
ravel_arr = reshaped_arr.ravel()
print(ravel_arr)

#transpose() function transposes the x and y values of a 2-dimensional matrix
transposed_arr = reshaped_arr.transpose()
print(transposed_arr)

#resize() works similarly to reshape() but changes the shape of the original array:

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [41]:
#Stacking Arrays

import numpy as np

arr1 = np.arange(1,10).reshape(3,3)

#Horizontal Stacking using hstack()
arr2 = 2*arr1

arr3 = np.hstack((arr1,arr2))
print(arr3)


#Horizontal stacking using concatenate()
arr4 = np.concatenate((arr1,arr2), axis=1)
print(arr4)


#Vertical stacking using vstack()
arr5 = np.vstack((arr1,arr2))
print(arr5)

#Vertical stacking using concatenate()
arr6 = np.concatenate((arr1,arr2), axis=0)
print(arr6)


#Depth stacking using dstack(). Stacks arrays with a third axis
arr7 = np.dstack((arr1,arr2))
print(arr7)

[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]
[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[[ 1  2]
  [ 2  4]
  [ 3  6]]

 [[ 4  8]
  [ 5 10]
  [ 6 12]]

 [[ 7 14]
  [ 8 16]
  [ 9 18]]]


In [46]:
#Stack data stored in one dimensional vectors

import numpy as np

arr1 = np.arange(4,7)
arr2 = 2*arr1

#Creating a column stack: Stores horizontal data from vectors into columns for the stack
arr_col_stack = np.column_stack((arr1,arr2))
print(arr_col_stack)


#Creating a row stack: Stores horizontal data from vectors into rows for the stack
arr_row_stack = np.row_stack((arr1,arr2))
print(arr_row_stack)

[[ 4  8]
 [ 5 10]
 [ 6 12]]
[[ 4  5  6]
 [ 8 10 12]]
