In [5]:
#Partitioning NumPy Arrays

import numpy as np

#Create an array
arr = np.arange(1,10).reshape(3,3)
print(arr)

#Perform horizontal splitting. split(arr,3,axis=1) performs the same task
arr_hor_split = np.hsplit(arr, 3)
print(arr_hor_split)

#Perform vertical splitting. split(arr,3,axis=0) performs the same task
arr_ver_split = np.vsplit(arr,3)
print(arr_ver_split)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [11]:
#Slicing NumPy Arrays
import numpy as np

arr = np.arange(0,10)
print(arr)

#slicing syntax similar to python lists: variable[start,stop,step/increments]
print(arr[3:6])
print(arr[3:])
print(arr[-3:])


[0 1 2 3 4 5 6 7 8 9]
[3 4 5]
[3 4 5 6 7 8 9]
[7 8 9]


In [19]:
#Boolean and fancy indexing
import numpy as np

arr = np.arange(21,41,2)
print(arr)
print(arr[arr>30])


#Fancy indexing works of arrays of multiple dimensions
arr = np.arange(1,21).reshape(5,4)
print(f"Original Array:\n {arr}")

indices = [1,2]
print(f"Selected 1st and 2nd Rows:\n {arr[indices]}")

indices = [2,3]
print(f"Selected 2nd and 3rd Rows:\n {arr[indices]}")


#Can use fancy indexing to create rows and column indices
row = np.array([1,2])
col = np.array([2,3])

print(f"Selected Sub-Array: {arr[row,col]}")

[21 23 25 27 29 31 33 35 37 39]
[31 33 35 37 39]
Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
Selected 1st and 2nd Rows:
 [[ 5  6  7  8]
 [ 9 10 11 12]]
Selected 2nd and 3rd Rows:
 [[ 9 10 11 12]
 [13 14 15 16]]
Selected Sub-Array: [ 7 12]


In [21]:
#Broadcasting allows mathematical manipulation of arrays

arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
print(arr1)
print(arr2)

print(arr1+arr2)
print(arr1*arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
